### ISSUE TITLE
Do we want to make this an Electron app?

### ISSUE THREAD

**Issue by mrfatguy** [mrfatguy/web-genname#2]
So this can be made available in form of true mobile and desktop (again! :) app rather than an on-line page?

1. Read basics:

    - [Lost Dutchman Mine → Application Building](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Building)

2. Prepare environment:

    - [Lost Dutchman Mine → Application Coding → Preparation](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Coding#preparation)
    - [Some old mail](https://mail.google.com/mail/u/0/%23inbox/KtbxLvhKRwfJHgklPgXsrRPqxGpqnsLbxV)

3. Read some more (extra tools):

    - [Electron.js → Docs → Tutorial → Packaging](https://www.electronjs.org/docs/latest/tutorial/tutorial-packaging)
    - [Electron Forge → Config → Plugins → Local Electron](https://www.electronforge.io/config/plugins/local-electron)
    - [GitHub: electron/build-tools](https://github.com/electron/build-tools)

4. Do some actual small change:

    - [Lost Dutchman Mine → Application Coding → Git Flow and Pull Requests](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Coding#git-flow-and-pull-requests)

5. Try building:

    - [Lost Dutchman Mine → Application Building → Windows](https://github.com/niner-games/lost-dutchman-mine/wiki/Application.-Building#windows)

But this would be more like _turn-single-page-into-electron-app_ than a long-term supported software with releases etc.

**Comment by MadejaMaciej** [comment]
I can help with that. It would be beneficial to do this, as it will generate files for web as well.

**Comment by mrfatguy** [comment]
Nah! On second thought, we have a lot of already existing, more important topics to generate new ones and spend extra time on a tiny stuff like this. 

Running this publicly under → https://mrfatguy.github.io/web-genname/ seems to be fine and enough.
