### ISSUE TITLE
Do we want to make this our official app?

### ISSUE THREAD

**Issue by mrfatguy** [mrfatguy/web-genname#3]
Following #2, consider making this an official Niner Games' app, putting this to our website and (if #2 successful) to app stores.

**Comment by MadejaMaciej** [comment]
I think it might be worth putting it there.

**Comment by mrfatguy** [comment]
Nah! On second thought, we have a lot of already existing, more important topics to generate new ones and spend extra time supporting tiny stuff like this.

Running this publicly under → https://mrfatguy.github.io/web-genname/ seems to be fine and enough.
